### ISSUE TITLE
Start a blog

### ISSUE THREAD

**Issue by dvberkel** [ClojureNauts/projects#2]
Maybe we should start a blog that gives details on the projects that we explore, e.g. report on our experiences with [clojurenauts-twitter-bot](https://github.com/ClojureNauts/clojurenauts-twitter-bot).

What do you think?

**Comment by dvberkel** [comment]
Maybe we could leverage the GitHub Wiki and relay that to the [ClojureNauts website](https://clojurenauts.github.io/). I think I have seen some project do it before.

**Comment by dvberkel** [comment]
I found [Cryogen](http://cryogenweb.org/index.html), a clojure based static blog generator

**Comment by pxlpnk** [comment]
I think we could go with the github pages solution. I guess Cryogen will allow us to do that!

**Comment by dvberkel** [comment]
@pxlpnk probably best indeed
